#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nfs-utils
Version  : 1.3.2
Release  : 3
URL      : http://downloads.sourceforge.net/project/nfs/nfs-utils/1.3.2/nfs-utils-1.3.2.tar.bz2
Source0  : http://downloads.sourceforge.net/project/nfs/nfs-utils/1.3.2/nfs-utils-1.3.2.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nfs-utils-bin
Requires: nfs-utils-doc
BuildRequires : LVM2-dev
BuildRequires : libcap-dev
BuildRequires : libevent-dev
BuildRequires : libnfsidmap-dev
BuildRequires : libtirpc-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : util-linux-dev

%description
This is nfs-utils, the Linux NFS userland utility package.
0. PROJECT RESOURCES
Home page:  http://sourceforge.net/projects/nfs/

%package bin
Summary: bin components for the nfs-utils package.
Group: Binaries

%description bin
bin components for the nfs-utils package.


%package doc
Summary: doc components for the nfs-utils package.
Group: Documentation

%description doc
doc components for the nfs-utils package.


%prep
%setup -q -n nfs-utils-1.3.2

%build
%configure --disable-static --without-tcp-wrappers --disable-gss --disable-ipv6 --disable-tirpc
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/var/lib/nfs/etab
/var/lib/nfs/rmtab
/var/lib/nfs/state
/var/lib/nfs/xtab

%files bin
%defattr(-,root,root,-)
/usr/bin/blkmapd
/usr/bin/exportfs
/usr/bin/mount.nfs
/usr/bin/mount.nfs4
/usr/bin/mountstats
/usr/bin/nfsdcltrack
/usr/bin/nfsiostat
/usr/bin/nfsstat
/usr/bin/osd_login
/usr/bin/rpc.idmapd
/usr/bin/rpc.mountd
/usr/bin/rpc.nfsd
/usr/bin/rpc.statd
/usr/bin/rpcdebug
/usr/bin/showmount
/usr/bin/sm-notify
/usr/bin/start-statd
/usr/bin/umount.nfs
/usr/bin/umount.nfs4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*
%doc /usr/share/man/man8/*
